name: Auto Update

on:
  schedule:
    - cron: '0 1 1 * *' # Runs once monthly
  workflow_dispatch:
    inputs:
      force:
        description: Force Update
        default: '0'
      dry:
        description: Dry Run
        default: '1'
      bump:
        type: choice
        description: Bump Version
        options:
          - patch
          - minor
          - major

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: git-actions/set-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 22
      - run: npm ci
      - name: Update
        run: |
          force="${{ github.event.inputs.force }}"
          dry="${{ github.event.inputs.dry }}"
          bump="${{ github.event.inputs.bump }}"
          if [ "$bump" = "" ]; then
            bump="patch"
          fi

          # Check for Updates
          status=0
          npm run check || status=$?
          if [ $status -eq 0 ] || [ $status -eq 4 ]; then
            if [ "$force" != "1" ]; then
              exit 0 # exit if there are no changes or if icons are only removed
            fi
          fi
          if [ $status -ge 4 ]; then
            bump="minor" # icons are removed from metadata API
          fi

          # Update
          npm run update
          npm --no-git-tag-version version "$bump"
          npm run init-pkgs
          npm i

          # Use 'git add --ignore-removal .' to keep deleted SVGs
          git add --all

          VERSION=$(node -p "require('./package.json').version")

          git commit -m "Auto Update $VERSION" || [ "$force" = "1" ] || exit 1

          git tag -a v$VERSION -m v$VERSION

          if [ "$dry" = "1" ]; then
            exit 0
          fi
          git push
          git push origin tag v$VERSION
          gh workflow run publish.yml --ref v$VERSION
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
